### ISSUE TITLE
Add dataset to REMS

### ISSUE THREAD

**Issue by dbampalikis** [GenomicDataInfrastructure/starter-kit-storage-and-interfaces#3]
As a GDI developer
I want to be able to have instructions on how to add a dataset to REMS
In order to be able to add a dataset and test the rest of the infrastructure

Try the instructions in the rems docker-compose part of the starter kit. If it's difficult to add a new dataset to the system that needs to be fed back to the PO of REMS so they can create more instructions that are more detailed and easy to follow.

A/C
- Get instructions for adding a dataset to REMS and test that it works on internal deployment

**Comment by nanjiangshu** [comment]
I have tested starting the REMS starter kit and creating a dataset by using the ready made and configured OIDC client. It is quite straightforward to add a dataset by following the instructions on the README. A minor problem is that the kit is not working well on Mac M1. It works much more smoothly on Linux. 

I have not tested with our own REMS, since that will require to register our own OIDC RP client at LS AAI and also needs a domain name for the REMS server.
